In [1]:
import torch

In [2]:
x = torch.empty(2,5)# 2 rows, 5 columns!!!!
x.size()
x.fill_(1.125)#put 1.125 everywhere 
#--> the underscore in the function name tells us that the fill function changes the value in the tensor
y = x.mean() #is a tensor of dim = 0
x.std()
x.sum()
x.sum().item()#returns value of tensor (.sum() returns a scalar tensor, so a tensor of dim = 0)

11.25

In [25]:
x = torch.empty(2,4,3)
x.normal_(0.0, 1)

tensor([[[-0.4128, -0.3185, -0.8973],
         [ 0.6671,  1.3512,  2.2935],
         [-0.4022, -0.7648,  0.1047],
         [-0.6007, -1.1779, -0.5554]],

        [[-1.2985, -1.9517,  1.4775],
         [ 2.1233,  0.4619, -1.0447],
         [ 0.6967,  1.1220, -0.4369],
         [-0.2589, -1.6207,  0.5889]]])

In [26]:
x.size()

torch.Size([2, 4, 3])

In [27]:
x = x.view(-1)

In [28]:
x.size()

torch.Size([24])

In [29]:
x

tensor([-0.4128, -0.3185, -0.8973,  0.6671,  1.3512,  2.2935, -0.4022, -0.7648,
         0.1047, -0.6007, -1.1779, -0.5554, -1.2985, -1.9517,  1.4775,  2.1233,
         0.4619, -1.0447,  0.6967,  1.1220, -0.4369, -0.2589, -1.6207,  0.5889])

In [31]:
x = torch.empty(2,3)
x.normal_(0.0, 1)

tensor([[-1.9252,  0.7870, -0.2167],
        [ 0.0370,  1.3609,  0.6323]])

In [32]:
x.view(1,2,3)

tensor([[[-1.9252,  0.7870, -0.2167],
         [ 0.0370,  1.3609,  0.6323]]])

In [34]:
x.expand(3,2,3)

tensor([[[-1.9252,  0.7870, -0.2167],
         [ 0.0370,  1.3609,  0.6323]],

        [[-1.9252,  0.7870, -0.2167],
         [ 0.0370,  1.3609,  0.6323]],

        [[-1.9252,  0.7870, -0.2167],
         [ 0.0370,  1.3609,  0.6323]]])